# Generated by Django 3.2.5 on 2022-03-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='moves',
            field=models.TextField(default='[]', null=True),
        ),
    ]
