# Generated by Django 3.2.5 on 2022-03-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_alter_gamesession_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
