# Generated by Django 3.2.5 on 2022-03-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_auto_20220313_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='name',
            field=models.TextField(default='My Game!'),
        ),
    ]
